---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::sourmash=4.9.4
  - conda-forge::sourmash_plugin_branchwater=0.9.14
  - pandas=2.2.3